/* Superthoughts pilot catalog. Mastered audio, no live-generation costs. */
window.STCatalog = [
 {id:'gratitude',title:'Morning gratitude',description:'Let one small, real thing set the tone for your day.',category:'morning',type:'guided',duration:390,src:'audio/gratitude-v6.mp3',cues:'audio/gratitude-v6-cues.json',visual:'gratitude',accent:'#e6b394',kicker:'A little appreciation'},
 {id:'begin-day',title:'Begin your day',description:'Find your footing and choose one thing to give your attention to.',category:'morning',type:'guided',duration:270,src:'audio/pilot-begin-day-v4.mp3',cues:'audio/pilot-begin-day-v4-cues.json',visual:'begin-day',accent:'#ecc080',kicker:'An easy beginning'},
 {id:'reset',title:'A little reset',description:'A short pause to feel your feet, find your breath, and begin again.',category:'reset',type:'guided',duration:180,src:'audio/pilot-reset-v4.mp3',cues:'audio/pilot-reset-v4-cues.json',visual:'reset',accent:'#99d0c3',kicker:'Room between things'},
 {id:'whole-body',title:'Whole-body relaxation',description:'An unhurried practice from the top of your head to the tips of your toes.',category:'reset',type:'guided',duration:450,src:'audio/whole-body-v7.mp3',cues:'audio/whole-body-v7-cues.json',visual:'whole-body',accent:'#b4a5dc',kicker:'Come back to yourself'},
 {id:'wind-down',title:'Wind down',description:'Let the pace soften. A little space at the end of the day.',category:'evening',type:'guided',duration:210,src:'audio/wind-down-v13.mp3',cues:'audio/wind-down-v13-cues.json',visual:'wind-down',accent:'#b3c19b',kicker:'Let the day settle'},
 {id:'warmth',title:'Warmth',description:'Low, rounded tones unfolding into a soft, resonant room. Only sound.',category:'sound',type:'sound',duration:360,src:'audio/pilot-warmth-v2.mp3',cues:null,visual:'warmth',accent:'#dc9b8b',kicker:'A soft place to land'},
 {id:'open-space',title:'Open space',description:'Floating harmonies, long echoes, and room to follow your own attention.',category:'sound',type:'sound',duration:480,src:'audio/pilot-open-space-v2.mp3',cues:null,visual:'open-space',accent:'#9bbde7',kicker:'Let your attention wander'},
 {id:'drift',title:'Drift',description:'A slow, low sound bath that settles gently into quiet.',category:'sound',type:'sound',duration:600,src:'audio/pilot-drift-v2.mp3',cues:null,visual:'drift',accent:'#b0a0dc',kicker:'A little further into quiet'},
 {id:'afterglow',title:'Afterglow',description:'Warm bowl tones and slow twilight harmonies. A little longer to let the day settle.',category:'evening',type:'sound',duration:720,src:'audio/afterglow-v2.mp3',cues:null,visual:'afterglow',accent:'#e6a18f',kicker:'Stay a little longer'},
 {id:'first-light',title:'First light',description:'Soft rising harmonies and open space. A wordless beginning, at your own pace.',category:'morning',type:'sound',duration:480,src:'audio/first-light-v2.mp3',cues:null,visual:'first-light',accent:'#98d6da',kicker:'A little light comes through'}
];
