/* Superthoughts pilot catalog. Mastered audio, no live-generation costs. */
window.STCatalog = [
 {id:'soft-place-to-land',title:'A soft place to land',description:'A spacious guided Warmth experience. Room for your body, your breath, and whatever you brought with you.',category:'reset',type:'guided',duration:570,src:'audio/soft-place-to-land-v5.mp3',cues:'audio/soft-place-to-land-v5-cues.json',visual:'warmth',accent:'#d99570',kicker:'Rest in Warmth'},
 {id:'gratitude',title:'Morning gratitude',description:'Let one small, real thing set the tone for your day.',category:'morning',type:'guided',duration:390,src:'audio/gratitude-v7.mp3',cues:'audio/gratitude-v7-cues.json',visual:'gratitude',accent:'#e6b394',kicker:'A little appreciation'},
 {id:'begin-day',title:'Begin your day',description:'Find your footing and choose one thing to give your attention to.',category:'morning',type:'guided',duration:270,src:'audio/pilot-begin-day-v7.mp3',cues:'audio/pilot-begin-day-v7-cues.json',visual:'begin-day',accent:'#ecc080',kicker:'An easy beginning'},
 {id:'reset',title:'A little reset',description:'A short pause to feel your feet, find your breath, and begin again.',category:'reset',type:'guided',duration:180,src:'audio/pilot-reset-v13.mp3',cues:'audio/pilot-reset-v13-cues.json',visual:'reset',accent:'#99d0c3',kicker:'Room between things'},
 {id:'still-enough-to-listen',title:'Still enough to listen',description:'Nine quiet minutes to be still, notice your breath, and perhaps hear your heartbeat.',category:'reset',type:'guided',duration:540,src:'audio/still-enough-to-listen-v5.mp3',cues:'audio/still-enough-to-listen-v5-cues.json',visual:'still-enough-to-listen',accent:'#d69465',kicker:'Listen inward'},
 {id:'whole-body',title:'Whole-body relaxation',description:'An unhurried practice from the top of your head to the tips of your toes.',category:'reset',type:'guided',duration:450,src:'audio/whole-body-v10.mp3',cues:'audio/whole-body-v10-cues.json',visual:'whole-body',accent:'#b4a5dc',kicker:'Come back to yourself'},
 {id:'after-conversation',title:'After a hard conversation',description:'Room to settle after something difficult. Nothing needs to be sorted out yet.',category:'reset',type:'guided',duration:480,src:'audio/after-a-hard-conversation-v4.mp3',cues:'audio/after-a-hard-conversation-v4-cues.json',visual:'after-conversation',accent:'#d39aae',kicker:'It can stay unfinished'},
 {id:'wind-down',title:'Wind down',description:'Let the pace soften. A little space at the end of the day.',category:'evening',type:'guided',duration:210,src:'audio/wind-down-v14.mp3',cues:'audio/wind-down-v14-cues.json',visual:'wind-down',accent:'#b3c19b',kicker:'Let the day settle'},
 {id:"enter-your-work",title:"Enter your work",description:"Arrive at your desk, choose one small beginning, and start from there.",category:"reset",type:"guided",duration:285,src:"audio/enter-your-work-v1.mp3",cues:"audio/enter-your-work-v1-cues.json",visual:"begin-day",accent:"#e3a978",kicker:"One small step"},
 {id:"awake-again",title:"Awake again",description:"For when you wake in the night. Feel your body, slow your breath, and let sleep come back.",category:"evening",type:"guided",duration:600,src:"audio/awake-again-v3.mp3",cues:"audio/awake-again-v3-cues.json",visual:"drift",accent:"#8f9fd6",kicker:"Back to rest"},
 {id:"letting-go-into-sleep",title:"Letting go into sleep",description:"Breathe out the day, feel your body grow heavy, and let sleep come. Twenty minutes of guidance, then ten of quiet sound.",category:"evening",type:"guided",duration:1800,src:"audio/letting-go-into-sleep-v2.mp3",cues:"audio/letting-go-into-sleep-v2-cues.json",visual:"drift",accent:"#7f8fcb",kicker:"Down into sleep"},
 {id:"frequency-of-abundance",title:"The frequency of abundance",description:"Settle your breath and tune into the place inside you where abundance already lives. Part of the Frequency series.",category:"reset",type:"guided",duration:665,src:"audio/frequency-of-abundance-v1.mp3",cues:"audio/frequency-of-abundance-v1-cues.json",visual:"afterglow",accent:"#e8b36f",kicker:"The Frequency series"},
 {id:'warmth',title:'Warmth',description:'Low, rounded tones unfolding into a soft, resonant room. Only sound.',category:'sound',type:'sound',duration:360,src:'audio/pilot-warmth-v2.mp3',cues:null,visual:'warmth',accent:'#dc9b8b',kicker:'A soft place to land'},
 {id:'open-space',title:'Open space',description:'Floating harmonies, long echoes, and room to follow your own attention.',category:'sound',type:'sound',duration:480,src:'audio/pilot-open-space-v2.mp3',cues:null,visual:'open-space',accent:'#9bbde7',kicker:'Let your attention wander'},
 {id:'drift',title:'Drift',description:'A slow, low sound bath that settles gently into quiet.',category:'sound',type:'sound',duration:600,src:'audio/pilot-drift-v2.mp3',cues:null,visual:'drift',accent:'#b0a0dc',kicker:'A little further into quiet'},
 {id:'afterglow',title:'Afterglow',description:'Warm bowl tones and slow twilight harmonies. A little longer to let the day settle.',category:'evening',type:'sound',duration:720,src:'audio/afterglow-v2.mp3',cues:null,visual:'afterglow',accent:'#e6a18f',kicker:'Stay a little longer'},
 {id:'first-light',title:'First light',description:'Soft rising harmonies and open space. A wordless beginning, at your own pace.',category:'morning',type:'sound',duration:480,src:'audio/first-light-v2.mp3',cues:null,visual:'first-light',accent:'#98d6da',kicker:'A little light comes through'}
];
